events {
    worker_connections 1024;
}
http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    server {
        listen 80;
        server_name _;
        root /usr/share/nginx/html;
        index index.html;
        location /api/ {
            proxy_pass https://vidflow-production-727a.up.railway.app/api/;
            proxy_http_version 1.1;
            proxy_ssl_server_name on;
            proxy_redirect off;
            proxy_set_header Host vidflow-production-727a.up.railway.app;
            proxy_set_header Connection "";
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_connect_timeout 30s;
            proxy_send_timeout 180s;
            proxy_read_timeout 180s;
        }
        location /static/ {
            proxy_pass https://vidflow-production-727a.up.railway.app/static/;
            proxy_http_version 1.1;
            proxy_ssl_server_name on;
            proxy_redirect off;
            proxy_set_header Host vidflow-production-727a.up.railway.app;
            proxy_set_header Connection "";
        }
        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
